/** Поля мастера «Уведомление о прибытии» — простые подписи для людей */
export const pribytieSchema = {
  procedureId: "pribytie",
  slug: "uvedomlenie-o-pribytii",
  title: "Уведомление о прибытии",
  steps: [
    {
      id: "person",
      title: "Кто приехал (иностранец)",
      fields: [
        { id: "lastName", label: "Фамилия", type: "text", required: true, hint: "Как в паспорте" },
        { id: "lastNameLat", label: "Фамилия латиницей", type: "text", required: true, hint: "Латинскими буквами, как в паспорте" },
        { id: "firstName", label: "Имя", type: "text", required: true },
        { id: "firstNameLat", label: "Имя латиницей", type: "text", required: true },
        { id: "middleName", label: "Отчество", type: "text", required: true, hint: "Если отчества нет — напишите «нет»" },
        { id: "middleNameLat", label: "Отчество латиницей", type: "text", required: true, hint: "Если нет — напишите «нет»" },
        { id: "citizenship", label: "Гражданство", type: "text", required: true, hint: "Страна паспорта. Если без гражданства — напишите «лицо без гражданства»" },
        { id: "birthDate", label: "Дата рождения", type: "date", required: true },
        {
          id: "sex",
          label: "Пол",
          type: "radio",
          required: true,
          options: [
            { value: "m", label: "Мужской" },
            { value: "f", label: "Женский" },
          ],
        },
        { id: "birthPlace", label: "Где родился", type: "text", required: true, hint: "Страна и город" },
      ],
    },
    {
      id: "docs",
      title: "Паспорт и въезд",
      fields: [
        { id: "docType", label: "Какой документ", type: "text", required: true, placeholder: "Паспорт" },
        { id: "docSeries", label: "Серия", type: "text", required: false },
        { id: "docNumber", label: "Номер", type: "text", required: true },
        { id: "docIssued", label: "Когда выдан", type: "date", required: true },
        { id: "docUntil", label: "Действует до", type: "date", required: false },
        {
          id: "extraDoc",
          label: "Есть виза, РВП или ВНЖ?",
          type: "text",
          required: false,
          hint: "Напишите: виза / РВП / вид на жительство. Если нет — оставьте пустым",
        },
        {
          id: "purpose",
          label: "Зачем приехал",
          type: "select",
          required: true,
          options: [
            { value: "работа", label: "Работа" },
            { value: "туризм", label: "Туризм" },
            { value: "частная", label: "В гости / к семье" },
            { value: "учеба", label: "Учёба" },
            { value: "деловая", label: "Деловая поездка" },
            { value: "служебная", label: "Служебная" },
            { value: "транзит", label: "Транзит" },
            { value: "гуманитарная", label: "Гуманитарная" },
            { value: "иная", label: "Другое" },
          ],
        },
        { id: "foreignPhone", label: "Телефон иностранца", type: "text", required: false },
        { id: "profession", label: "Кем работает / чем занимается", type: "text", required: false },
        { id: "entryDate", label: "Дата въезда в Россию", type: "date", required: true },
        { id: "stayUntil", label: "До какой даты будет жить здесь", type: "date", required: true },
        { id: "migrationCard", label: "Миграционная карта: серия и номер", type: "text", required: false },
      ],
    },
    {
      id: "address",
      title: "Адрес, где живёт",
      fields: [
        {
          id: "previousAddress",
          label: "Где жил в России раньше",
          type: "textarea",
          required: false,
          hint: "Если нигде не жил — напишите «нет» или оставьте пустым",
        },
        {
          id: "address",
          label: "Адрес сейчас",
          type: "textarea",
          required: true,
          hint: "Город, улица, дом, квартира. Можно с индексом",
        },
        { id: "cadastral", label: "Кадастровый номер квартиры (если знаете)", type: "text", required: false },
      ],
    },
    {
      id: "host",
      title: "Кто дал жильё",
      fields: [
        {
          id: "hostKind",
          label: "Кто принимает",
          type: "radio",
          required: true,
          options: [
            { value: "person", label: "Человек" },
            { value: "org", label: "Фирма / организация" },
          ],
        },
        {
          id: "hostName",
          label: "ФИО человека или название фирмы",
          type: "text",
          required: true,
          hint: "Для человека: фамилия имя отчество через пробел",
        },
        { id: "hostDoc", label: "Паспорт или документ принимающего", type: "text", required: true, hint: "Например: паспорт 9200 123456" },
        {
          id: "hostAddress",
          label: "Адрес принимающего",
          type: "textarea",
          required: true,
        },
        {
          id: "filer",
          label: "Кто отнесёт бланк в МВД / МФЦ / на почту",
          type: "radio",
          required: true,
          options: [
            { value: "host", label: "Тот, кто дал жильё" },
            { value: "self", label: "Сам иностранец" },
          ],
        },
      ],
    },
  ],
};
